# -*- coding: utf-8 -*-
"""Customer Churn Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_1uQZ40OUBIoQKJOaAcQ3whMVmPCxo9_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "Customer_ID":[101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Age":[22,25,30,35,40,28,50,45,33,27,
           38,29,41,36,26,48,32,37,44,31],

    "Subscription_Months":[2,5,24,18,36,3,48,30,12,4,
                           20,8,40,16,6,50,14,22,28,10],

    "Login_Frequency":[2,4,25,20,30,1,28,22,12,3,
                       18,7,26,15,5,32,14,19,24,8],

    "Support_Tickets":[8,5,1,2,0,10,0,1,3,7,
                       2,4,1,3,6,0,2,1,1,4],

    "Monthly_Spend":[100,150,700,650,900,80,950,750,500,120,
                     600,300,850,550,250,1000,450,620,780,350],

    "Churn":[1,1,0,0,0,1,0,0,0,1,
             0,1,0,0,1,0,0,0,0,1]
}

df = pd.DataFrame(data)

df.head()

print(df.shape)

df.info()

df.describe()

churn_count = df["Churn"].value_counts()

print(churn_count)

churn_count.plot(kind="bar")

plt.title("Customer Churn Distribution")
plt.ylabel("Count")
plt.show()

df.groupby("Churn").mean(numeric_only=True)

df.groupby("Churn")["Login_Frequency"].mean()

df.groupby("Churn")["Login_Frequency"].mean().plot(kind="bar")

plt.title("Average Login Frequency")
plt.ylabel("Logins")
plt.show()

df.groupby("Churn")["Subscription_Months"].mean()

df.groupby("Churn")["Subscription_Months"].mean().plot(kind="bar")

plt.title("Subscription Duration")
plt.ylabel("Months")
plt.show()

df.groupby("Churn")["Support_Tickets"].mean()

df.groupby("Churn")["Support_Tickets"].mean().plot(kind="bar")

plt.title("Support Tickets vs Churn")
plt.ylabel("Tickets")
plt.show()

df.groupby("Churn")["Monthly_Spend"].mean()

df.groupby("Churn")["Monthly_Spend"].mean().plot(kind="bar")

plt.title("Monthly Spending")
plt.ylabel("Amount")
plt.show()

correlation = df.corr(numeric_only=True)

print(correlation["Churn"])

# Findings

# 1. Customers with low login frequency are more likely to churn.

# 2. Customers with shorter subscription durations show higher churn rates.

# 3. Customers raising more support tickets tend to churn more often.

# 4. Customers with lower monthly spending have a higher probability of leaving.

# 5. Long-term and highly engaged customers are less likely to churn.

# Recommendations

# 1. Increase engagement through notifications and personalized content.

# 2. Offer loyalty rewards for long-term subscribers.

# 3. Improve customer support response times.

# 4. Provide special discounts to inactive customers.

# 5. Identify low-engagement users early and launch retention campaigns.

df.to_csv("customer_churn_analysis.csv", index=False)

print("Analysis completed successfully.")