# -*- coding: utf-8 -*-
"""Data Cleaning & Structural Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGwc0xzWOPkWLPvQ5RMpFg3OaghbEWcj
"""

import pandas as pd
import numpy as np
import re

data = {
    "ID": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
    "Name": [
        "John Smith",
        "john smith",
        "Sarah Johnson",
        "Mike Brown",
        "Emma Wilson",
        "David Lee",
        " Anna Taylor ",
        "Chris Evans",
        "Robert King",
        "Lisa White",
        "JOHN SMITH",
        "Emily Davis",
        "Mark Allen",
        "Sophia Clark",
        "James Scott"
    ],
    "Email": [
        "john@gmail.com",
        "john@gmail.com",
        None,
        "mike@gmail.com",
        "emma@gmail.com",
        "david@gmail.com",
        "anna@gmail.com",
        "chrisgmail.com",
        "robert@gmail.com",
        "lisa@gmail.com",
        "john@gmail.com",
        "emily@gmail.com",
        "mark@gmail.com",
        "sophia@gmail",
        "james@gmail.com"
    ],
    "Age": [
        23,23,25,None,22,150,24,27,29,21,23,26,None,28,17
    ],
    "Department": [
        "IT","IT","HR","Finance","Marketing","IT","HR",
        "Finance",None,"Marketing","IT","HR","IT",
        "Finance","Marketing"
    ],
    "Salary": [
        45000,45000,38000,52000,41000,60000,39000,
        48000,55000,None,45000,40000,47000,53000,35000
    ],
    "Join_Date": [
        "12/01/2025","2025-01-12","15-02-2025",
        "2025/03/10","2025-04-01","01/05/2025",
        "2025-06-15","2025-07-20","2025-08-01",
        "2025-09-12","12-Jan-2025","2025/10/05",
        "2025-11-11","2025-12-01","2025-12-15"
    ]
}

df = pd.DataFrame(data)

print("Raw Dataset")
df.head()

print("Shape of Dataset:", df.shape)

print("\nInformation:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("Duplicate Rows:", df.duplicated().sum())

df[df.duplicated()]

df["Name"] = df["Name"].str.strip()

df["Name"] = df["Name"].str.title()

df[["Name"]].head()

df = df.drop_duplicates()

print("Duplicates Removed")
print("New Shape:", df.shape)

median_age = df["Age"].median()

df["Age"] = df["Age"].fillna(median_age)

median_salary = df["Salary"].median()

df["Salary"] = df["Salary"].fillna(median_salary)

df["Department"] = df["Department"].fillna("Unknown")

df["Email"] = df["Email"].fillna("unknown@email.com")

print(df.isnull().sum())

pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'

df["Valid_Email"] = df["Email"].apply(
    lambda x: bool(re.match(pattern, str(x)))
)

print("Invalid Emails:")
df[~df["Valid_Email"]]

invalid_age = df[
    (df["Age"] < 18) |
    (df["Age"] > 120)
]

print("Invalid Ages:")
invalid_age

df.loc[
    (df["Age"] < 18) |
    (df["Age"] > 120),
    "Age"
] = median_age

df

df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
)

df["Join_Date"] = df["Join_Date"].dt.strftime("%Y-%m-%d")

df[["Join_Date"]].head()

print("Final Missing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

print("\nData Types")
print(df.dtypes)

print("Cleaned Dataset")
df

df.to_csv("cleaned_data.csv", index=False)

print("Cleaned dataset saved successfully!")

"""Conclusion

The dataset was successfully cleaned and validated.

Actions Performed:
* Removed duplicate records
* Handled missing values
* Standardized text formatting
* Standardized date formats
* Validated email formats
* Corrected invalid age values
* Verified dataset structure

Result:
The final dataset is clean, consistent, and ready for analysis.
"""