# -*- coding: utf-8 -*-
"""Geospatial Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UMeb1QapxybJnLNjx1cBgzohyfWoveo
"""

import pandas as pd
import matplotlib.pyplot as plt

data = {
    "City": [
        "Hyderabad",
        "Bangalore",
        "Chennai",
        "Mumbai",
        "Delhi",
        "Pune",
        "Kolkata",
        "Ahmedabad",
        "Vizag",
        "Vijayawada"
    ],

    "Sales": [
        85000,
        95000,
        70000,
        110000,
        105000,
        65000,
        55000,
        50000,
        75000,
        72000
    ],

    "Existing_Stores": [
        8,
        10,
        7,
        12,
        11,
        4,
        3,
        2,
        1,
        1
    ],

    "Latitude": [
        17.3850,
        12.9716,
        13.0827,
        19.0760,
        28.7041,
        18.5204,
        22.5726,
        23.0225,
        17.6868,
        16.5062
    ],

    "Longitude": [
        78.4867,
        77.5946,
        80.2707,
        72.8777,
        77.1025,
        73.8567,
        88.3639,
        72.5714,
        83.2185,
        80.6480
    ]
}

df = pd.DataFrame(data)

df

print(df.shape)

df.info()

df.describe()

df.plot(
    x="City",
    y="Sales",
    kind="bar"
)

plt.title("Sales by City")
plt.ylabel("Sales")

plt.show()

df.plot(
    x="City",
    y="Existing_Stores",
    kind="bar"
)

plt.title("Store Presence")

plt.ylabel("Number of Stores")

plt.show()

df["Expansion_Score"] = (
    df["Sales"] /
    df["Existing_Stores"]
)

df.sort_values(
    "Expansion_Score",
    ascending=False
)

top_cities = df.sort_values(
    "Expansion_Score",
    ascending=False
)

top_cities[[
    "City",
    "Sales",
    "Existing_Stores",
    "Expansion_Score"
]]

df.sort_values(
    "Expansion_Score",
    ascending=False
).plot(
    x="City",
    y="Expansion_Score",
    kind="bar"
)

plt.title("Business Expansion Opportunity")

plt.ylabel("Expansion Score")

plt.show()

!pip install folium

import folium

india_map = folium.Map(
    location=[20.5937,78.9629],
    zoom_start=5
)

for _, row in df.iterrows():

    folium.Marker(
        location=[
            row["Latitude"],
            row["Longitude"]
        ],

        popup=f"""
        City: {row['City']}
        Sales: {row['Sales']}
        Stores: {row['Existing_Stores']}
        """

    ).add_to(india_map)

india_map

df.to_csv(
    "geospatial_analysis.csv",
    index=False
)

print("Analysis Completed Successfully")