# -*- coding: utf-8 -*-
"""Web Traffic Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WT0gnZ334IeXA5IIs7Uv3ifelG_90gSh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "User_ID":[1,2,3,4,5,6,7,8,9,10,
               11,12,13,14,15,16,17,18,19,20],

    "Page_Views":[2,3,10,8,12,1,15,9,4,2,
                  14,11,6,5,13,3,7,10,12,4],

    "Session_Duration_Min":[1,2,12,10,15,0.5,18,11,4,1,
                            16,14,6,5,17,2,8,13,15,3],

    "Bounce":[1,1,0,0,0,1,0,0,1,1,
              0,0,0,1,0,1,0,0,0,1],

    "Pages_Visited":[
        "Home",
        "Home",
        "Home→Products→Cart",
        "Home→Products",
        "Home→Products→Cart→Checkout",
        "Home",
        "Home→Products→Cart→Checkout",
        "Home→Products→Cart",
        "Home→Blog",
        "Home",
        "Home→Products→Checkout",
        "Home→Products→Cart",
        "Home→Blog→Products",
        "Home→Blog",
        "Home→Products→Cart→Checkout",
        "Home",
        "Home→Products",
        "Home→Products→Cart",
        "Home→Products→Cart→Checkout",
        "Home→Blog"
    ]
}

df = pd.DataFrame(data)

df.head()

print(df.shape)

df.info()

df.describe()

print("Total Users:", len(df))

print("Total Page Views:", df["Page_Views"].sum())

print("Average Session Duration:",
      round(df["Session_Duration_Min"].mean(),2),"minutes")

df["Page_Views"].plot(kind="hist")

plt.title("Distribution of Page Views")
plt.xlabel("Page Views")
plt.show()

df["Session_Duration_Min"].plot(kind="hist")

plt.title("Session Duration Distribution")
plt.xlabel("Minutes")
plt.show()

bounce_rate = (
    df["Bounce"].sum()/len(df)
)*100

print("Bounce Rate:", round(bounce_rate,2),"%")

df["Bounce"].value_counts().plot(kind="bar")

plt.title("Bounce Analysis")
plt.show()

journey_counts = df["Pages_Visited"].value_counts()

print(journey_counts)

journey_counts.plot(kind="bar")

plt.title("Most Common User Journeys")

plt.ylabel("Users")

plt.show()

dropoffs = df[
    df["Pages_Visited"]=="Home"
]

print("Users Dropping at Homepage:")
print(len(dropoffs))

df["Engagement"] = np.where(
    df["Session_Duration_Min"] > 10,
    "High",
    "Low"
)

df["Engagement"].value_counts()

df["Engagement"] = np.where(
    df["Session_Duration_Min"] > 10,
    "High",
    "Low"
)

df["Engagement"].value_counts()

df["Engagement"].value_counts().plot(kind="bar")

plt.title("User Engagement")

plt.show()

df.to_csv(
    "web_traffic_analysis.csv",
    index=False
)

print("Analysis Completed Successfully")